name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: qt5builder/ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake CMakeLists.txt
    - name: make
      run: make
