name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: qt
    - run: apt-get install qt5-default
    - name: cmake
      run: cmake CMakeLists.txt
    - name: make
      run: make
