name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    
    - name: qt
      uses: "docker://theshadowx/qt5/dockerfile.latest"
      run: cmake CMakeLists.txt && make
