on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A build job
    steps:
    - name: checkout step
      id: checkout
      uses: actions/checkout@v1
    - name: C/C++ Build (CMake)
      uses: nathanesau/build-action@1 # github marketplace
      run: cmake CMakeLists.txt && make
