on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A build job
    steps:
    - name: checkout step
      id: checkout
      uses: actions/checkout@v1
    - name: build step
      id: build
      uses: actions/build-action@v1 # github marketplace
