name: C/C++ CI

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    
    - name: C/C++ Build (CMake)
      uses: nathanesau/build-action@1 # github marketplace
      run: cmake CMakeLists.txt && make
